---
# tasks file for clavessh

#########################################
#Claves RSA 
#########################################

  - name: add sshkey {{ ssh_users.name }}
    authorized_key:
      user: admin
      state: present
      key: "{{ lookup('file', ssh_users.file) }}"


