---
# tasks file for clavessh

#########################################
#Claves RSA 
#########################################

  - name: add sshkey {{ user.name }}
    authorized_key:
      user: admin
      state: present
      key: "{{ lookup('file', "{{ user.file }}" ) }}"


