---
# tasks file for clavessh

#########################################
#Claves RSA 
#########################################

  - name: add sshkey "{{ item.name }}"
    authorized_key:
      user: admin
      state: present
      key: "{{ lookup('file', item.file) }}"
      with_items: "{{ ssh_users }}"


