---
# tasks file for 00update
pre_tasks:
- name: Muestra familia SO
    debug:
      msg: "S.O. {{ ansible_facts['os_family'] }}"

- name: Actualiza Centos y RedHat
  import_tasks: centos_rhel.yml
  when: ansible_distribution_file_variety == "RedHat"

- name: Actualiza Debian
  import_tasks: debian.yml
  when: ansible_distribution_file_variety == "Debian"

# Reiniciamos el sistema. TODAS las distros.
- name: System reboot
  when: restart_after_update|bool
  reboot:
  msg: "Reboot initiated by Ansible after System Update."
    reboot_timeout: 600
    test_command: "whoami"
    post_reboot_delay: 15
...

